### ISSUE TITLE
formCollection() Form/View/Helper

### ISSUE THREAD

**Issue by moxoder** [zendframework/zend-view#10]
When designing, I discovered that in view, when I use the helper $ this-> row () through a partial, then the use of the $ this-> collection (), element collection is transferred to the partial row, not korektno, this code after use pfrtial a row and before using the collection must be reset partial.

index.phtml
...
<?php echo $this->formRow($this->form->get('retainImages'), NULL, NULL, 'shop/partial/productEditCheckbox.phtml') ?>

<?php $this->formCollection()->setElementHelper($this->formRow()->setPartial(NULL)); ?>
<dd><?php echo $this->formCollection($this->form->get('images')) ?></dd>

**Comment by moxoder** [comment]
Проблема существует

**Comment by froschdesign** [comment]
@moxoder 
Please move this ticket to the issue tracker of `Zend\Form`, because the `formCollection` is not a part of the `Zend\View` component. After moving the ticket, please close this one. Thanks!

(Btw. please write your messages in English)
