### ISSUE TITLE
HeadTitle helper documentation is too complicated

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zend-view#109]
For a basic usage the module class is not needed.

https://docs.zendframework.com/zend-view/helpers/head-title/

**Comment by tekielee** [comment]
I new to contributing to the Zend Framework. Could please provide some instructions/help on how to start with this easy ticket. I have installed the zend-view on my virtualbox. I am reading the source codes right now. Thanks.

**Comment by froschdesign** [comment]
@tekielee 
You find instructions in the [`CONTRIBUTING.md`](https://github.com/zendframework/zend-view/blob/master/CONTRIBUTING.md) file, which is included in every repository.

The documentation should included the basic and simple usage. For example:

> In a layout script:
> ```php
> <?= $this->headTitle('My Website')->setSeparator(' - ') ?>
> ```
>
> In a view script:
> ```php
> $this->headTitle('My page title');
> ```
>
> Output:
> ```html
> <title>My page title - My Website</title>

And code examples to:

* `append`
* `prepend`
* `setAutoEscape`
* `renderTitle`

**Comment by tekielee** [comment]
I see just make it simpler and easier to understand. I'll give it a try. Thanks.
