### ISSUE TITLE
How do I set form helper plugin without HelperConfig?

### ISSUE THREAD

**Issue by dennis-fedco** [zendframework/zend-view#111]
I am using a stand-alone PhpRendered, outside of ZF stack.  I used to have the following line working, to render forms:

    echo $this->getRenderer()->form($form);

I would set the `form` and other view plugins with the help of `HelperConfig`.  Without using `HelperConfig` (which has been deprecated), how can I still make the above line work?

Currently I get an error:

> Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: A plugin by the name "form" was not found in the plugin manager Zend\View\HelperPluginManager in vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php on line 131

The old way to activate form view plugins I was using was this:

    //activates Form renderer plugins in View
    protected function setFormRenderer()
    {
        //extract view plugin manager component from our Renderer
        $viewPluginManager = $this->renderer->getHelperPluginManager();

        // service that sets up View Plugins for forms inside our Renderer
        $formConfig = new \Zend\Form\View\HelperConfig();
        $formConfig->configureServiceManager($viewPluginManager);
    }

**Comment by dennis-fedco** [comment]
Specifically here is a self-contained example that should be runnable, which uses the deprecated `HelperConfig` to render a form:
https://gist.github.com/dennis-fedco/f620477d3969a0eba4a60ffc09cf630e

I'm still not sure how to rewrite it using modern tech.

**Comment by froschdesign** [comment]
Use the `ConfigProvider` of zend-form:

```php
$phpRenderer->getHelperPluginManager()->configure(
    (new Zend\Form\ConfigProvider())->getViewHelperConfig()
);
```
