### ISSUE TITLE
PhpRenderer renders previous content when false is provided

### ISSUE THREAD

**Issue by porebskk** [zendframework/zend-view#120]
Hello,

First thanks for this wonderful framework, I appreciate the effort everybody is putting into this project. Today i encounterd an unexpected behaviour. Allthough its not part of PhpRenderers::render signature, the renderer will return the previously generated content when false is provided as $nameOrModel parameter.
I would expect that the renderer is trying to be as stateless as possible. Is this something that can be categorized as misuse of the class or a behaviour that needs fixing?  
The same output would occur if a parameter would be provided that counts as falsy see:
`while ($this->__template = array_pop($this->__templates)) {`  
  
If this is something that needs fixing I could provide tests and a fix.

Kind regards

**Comment by weierophinney** [comment]
@porebskk Could you at the least create a pull request with a pull request demonstrating the issue? That would then allow us to verify/validate; if you include a fix, that also allows us to validate the fix against the test.

Thanks!
