### ISSUE TITLE
Child-view gets rendered twice

### ISSUE THREAD

**Issue by SuperDaifuku** [zendframework/zend-view#124]
I've noticed that my child-view gets rendered twice for some reasons. Here is a simple test-case:

Let's assume I've two controllers, ControllerA and ControllerB. I'm forwarding the action forwardTestAction from ControllerA to ControllerB and display the view returned from ControllerB as a child-view.

ControllerA::forwardTestAction()

```
public function forwardTestAction()
{
    $childView = $this->forward()->dispatch(ControllerB::class, [
        'action' => 'forward-test',
    ]);

    $mainView = new ViewModel();
    $mainView->addChild($childView, 'content');

    return $mainView;
}
```

ControllerB::forwardTestAction()

```
public function forwardTestAction()
{
    $number = new \stdClass();
    $number->a = 10.4;

    $view = new ViewModel([
        'number' => $number,
    ]);
    return $view;
}
```
Template forward-test.phtml of ControllerA

`<?= $content; ?>`

Template forward-test.phtml of ControllerB
```
<?php
    $number->a = $this->currencyFormat($number->a);
    echo $number->a;
```

The currencyFormat plugin throws an exception, because number gets formatted twice. The reason is because the child-view itself gets rendered twice - the rendered html is displayed only once though

That's a really weird behaviour and causes not only performance issues but also many other problems e.g. numberFormatting etc.

**Comment by froschdesign** [comment]
@SuperDaifuku 
> The currencyFormat plugin throws an exception, because number gets formatted twice.

Sorry, but I can not reproduce the problem. No exception thrown.

- zend-view 2.9.0
- zend-i18n 2.7.4

> ```php
> $number->a = $this->currencyFormat($number->a);
> ```

This ends in `false`.

**Comment by SuperDaifuku** [comment]
@froschdesign I'm using zend-view 2.8.1 and zend-i18n 2.7.3 (zendframework 3.0.0)

It actually doesn't throw an exception but a warning.

I'm 100% sure the child-view template gets rendered twice at least in my case - maybe I should test it on a completely fresh setup.

**Comment by froschdesign** [comment]
> It actually doesn't throw an exception but a warning.

**Comment by leolicai** [comment]
Yep, I have the same problem.
On the module.php add a dispatch listener.
If a action use forward()->diapatch() to other controller and action(eg: ControllerB::ActionB).
And in the modlue listener, use:
$event->getViewModel()->getTemplate() get the layout.
foreach($event->getViewModel()->getchildren() as $child) {
     Logger::Info($child->getTemplate()); //There can logger ControllerB/ActionB template twice!!!
}
And important. If in ControllerA at ActionB use forward()->dispatch() to ControllerA::ActionC.
There will not ben dispatch twice.
Only in ControllerA's some action forword()->dispatch() to other controller and other action. There will dispatch twice.

**Comment by froschdesign** [comment]
@leolicai
This behaviour is correct, because the `MvcEvent::EVENT_DISPATCH` is called again with `$this->forward()->dispatch()`.
You can [detach your listener](https://github.com/zendframework/zend-mvc/blob/master/src/Controller/Plugin/Forward.php#L96) or use a different event. For rendering the event [`MvcEvent::EVENT_RENDER`](https://docs.zendframework.com/zend-mvc/mvc-event/#mvceventevent_render-render) is a good choice.

**Comment by froschdesign** [comment]
@SuperDaifuku 
I can not reproduce the warning. Please recheck with new versions and see also my previous comment.

Closing due inactivity.
