### ISSUE TITLE
navigation()->menu() Navigation menu helper

### ISSUE THREAD

**Issue by bogutskyy** [zendframework/zend-view#13]
Sometimes developers want to make customization of menu in the output. For example, add bootstrap or other icon ``<i class="icon-user"></i>`` to menu item. It would be useful to be able to specify a template of menu item, like "{icon} {link} {other_content}", where {link} - ``<a>`` tag, generated in method ``htmlify()``. Content for placeholders can be passed in page params or menu helper params. Some placeholders out of box, like {link}, can be required in template.

**Comment by bogutskyy** [comment]
Menu items links may be more customizable if tags <a> and </a>  make as different placeholders. Then will be a possibility paste something in link, together with label.
<a href="#">something bebore label  LABEL</a> = {startLink}something bebore label {label}{endLink}

**Comment by froschdesign** [comment]
You can add any HTML elements to a label:

Configuration:
```php
'navigation' => [
    'default' => [
        'github' => [
            'label' => '<i class="icon-github"></i> GitHub',
            'href'  => '#',
        ],
    ],
],
```
and in a layout script:
```php
echo $this->navigation('navigation')->menu()->escapeLabels(false);
```

Or use a [partial script](https://docs.zendframework.com/zend-navigation/helpers/menu/#rendering-a-custom-menu-using-a-partial-view-script) or [pure CSS](https://davidwalsh.name/font-awesome-tags).

**Comment by froschdesign** [comment]
I think there are enough options to add icons or other elements.
