### ISSUE TITLE
Setting charset in Doctype::XHTML1_RDFA fails

### ISSUE THREAD

**Issue by basz** [zendframework/zend-view#134]
I'm getting an error when I set the charset on a rdfa document. Is that expected? Or an oversight?

```
        // set doctype
        $this->helperPluginManager->get('doctype')
            ->setDoctype(\Zend\View\Helper\Doctype::XHTML1_RDFA);

$this->helperPluginManager->get('headMeta')
            ->setCharset('utf-8');
```

```
Invalid value passed to set; please use setMeta()
./vendor/zendframework/zend-view/src/Helper/HeadMeta.php:442
```

Further; following the suggestion in the error gives me an error too.

```
$this->helperPluginManager->get('headMeta')
         ->setMeta('charset', 'utf-8');
```

```
Method "setMeta" does not exist
./vendor/zendframework/zend-view/src/Helper/Placeholder/Container/AbstractStandalone.php:83
```

**Comment by samsonasik** [comment]
the source of error seems came from https://github.com/zendframework/zend-view/blob/4d9954c05a3981ca711bd55932dc1d2b55580392/src/Helper/HeadMeta.php#L337-L342

**Comment by froschdesign** [comment]
@basz 
> Is that expected?

Right, because XHTML has no attribute `charset` for the meta element.
Use the attribute `http-equiv`:

```php
$this->headMeta()->appendHttpEquiv('Content-Type', 'application/xhtml+xml; charset=utf-8');
```

**Comment by froschdesign** [comment]
We should add a check or an `Exception` for this case.

**Comment by samsonasik** [comment]
@basz @froschdesign I've created PR #137 for it.

**Comment by basz** [comment]
thanks all!

**Comment by froschdesign** [comment]
@basz 
Thanks for reporting! 👍
