### ISSUE TITLE
RegistryKey of Zend Framework 1 used?

### ISSUE THREAD

**Issue by holtkamp** [zendframework/zend-view#145]
It seems some ZF1 code is still in the View Helper: 

https://github.com/zendframework/zend-view/search?q=regKey

is this on purpose or can it be removed safely?

**Comment by Xerkus** [comment]
Yep, that is a dead code.

**Comment by samsonasik** [comment]
@holtkamp I've created #147 for it

**Comment by holtkamp** [comment]
@samsonasik awesome, did not find time to dive into this 🤔
