### ISSUE TITLE
PhpRenderer generates warning level log with helpers which accepts reference as parameter

### ISSUE THREAD

**Issue by Zebercet** [zendframework/zend-view#149]
If we have a view helper which accepts reference as parameter, PhpRenderer generates warning level log as `MyHelper::__invoke() expected to be a reference, value given` at
[PhpRenderer#397](https://github.com/zendframework/zend-view/blob/master/src/Renderer/PhpRenderer.php#L397) line. I guess __call method brokes reference.

**Comment by froschdesign** [comment]
Quite simple:

1. Do not use a reference as parameter.
2. Do not use the  `__call` method.

Use number one! 😃

**Comment by froschdesign** [comment]
Please provide a valid use case why the reference is needed and why a simple return value is not an option.
Otherwise we must close this issue as "won't fix".

**Comment by Ocramius** [comment]
By-ref helpers method support is a giant can of worms that I'd rather not open at all: let's please not go down the rabbit hole there.

Yes, any `callable` should be a valid helper, but by-ref methods will break on basically any kind of function composition, and that is not just in this component, but with PHP in general.

Closing here as `won't fix`.
