### ISSUE TITLE
Fluent Interface missing on ConsoleModel::setErrorLevel

### ISSUE THREAD

**Issue by porebskk** [zendframework/zend-view#152]
Hello,

contrary to almost all other setter methods on classes that implement the ModelInterface, ConsoleModel::setErrorLevel ist not returning itself when the method is called.
I would assume that it would return `$this`. I'll be adding a test and a simple fix.

Best regards

**Comment by porebskk** [comment]
I created a PR see #153

**Comment by weierophinney** [comment]
Fixed with #153
