### ISSUE TITLE
Problems in the hosting.... but in my localhorst is working ok

### ISSUE THREAD

**Issue by JorgeBorda** [zendframework/zend-view#161]
Dear Friends.....
In my public hosting, I have a subdomain "sigi" in the xxxxxxxx.org website.

I develop that web in local, in my localhost of my PC. and is working OK. no any problems

I copy all files from my localhost to the area of the subdomain of my hosting..... 

Some options of my ZF2 aplication are not working…. in the hosting place, but in my PC (my localhost) are working OK

A) the source code is the same….. is copy one of the other..

Why is the problem..... what i do not define in the hosting???

The error is: Fatal error: Uncaught exception 'Zend\View\Exception\RuntimeException' with message 'Zend\View\Renderer\PhpRenderer::render: Unable to render template "layout/Application"; resolver could not resolve to a file' in /home/xxxxxxx/public_html/subdominios/sigi.yyyyyyyyy.org/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php:493 Stack trace: #0 /home/xxxxxxx/public_html/subdominios/sigi.yyyyyyyyy.org/vendor/zendframework/zend-view/src/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel)) #1 /home/xxxxxxx/public_html/subdominios/sigi.yyyyyyyyy.org/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel)) #2 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent)) #3 /home/xxxxxxx/public_html/subdominios/sigi.yyyyyyyyy.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #4 /home/xxxxxxx/ in /home/xxxxxxx/public_html/subdominios/sigi.yyyyyyyyy.org/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php on line 493

I do know  what to do....... does some bady had or know  this issue ???

Thanks a lot

**Comment by samuelnogueira** [comment]
Are you using Windows in your local dev environment, and Linux on the web server? If so, it could just be a case of fixing the CaSiNg in the template path or name: 
The template path `'layout/Application'` can be resolved on Windows because paths are not case sensitive, but can't in Linux because `Application.phtml` file does not exist, but `application.phtml` does.

**Comment by froschdesign** [comment]
@samuelnogueira's should fix your problem.
But keep in mind, this is an issue tracker. For questions or support please use the [chat](url) or the [forum](https://discourse.zendframework.com/). Thanks!

**Comment by JorgeBorda** [comment]
thanks  Iwill check

**Comment by JorgeBorda** [comment]
Yes..... you are write, a lot of thanks.......
