### ISSUE TITLE
zend-json required only as dev dependency

### ISSUE THREAD

**Issue by reinfi** [zendframework/zend-view#163]
Hey there,

why is zend-json only required as dev dependency, although the JsonModel in this package has a dependency on it?

Could it be moved to normal dependencies?

**Comment by froschdesign** [comment]
@reinfi 
It is only a _soft_ dependency and therefore it is included in the suggest section of the composer file.

https://github.com/zendframework/zend-view/blob/651621d82df0c70664e476481d53fe3b98989a78/composer.json#L53

**Comment by froschdesign** [comment]
I found a problem: the `JsonModel` may be optional, but zend-json is also used in the `Json` view helper and in the `AbstractHtmlElement`:

https://github.com/zendframework/zend-view/blob/master/src/Helper/Json.php
https://github.com/zendframework/zend-view/blob/651621d82df0c70664e476481d53fe3b98989a78/src/Helper/AbstractHtmlElement.php#L79

**Comment by samsonasik** [comment]
I've created PR #169 for it
