### ISSUE TITLE
Create <link rel=preload> with headLink() helper

### ISSUE THREAD

**Issue by tcelestino** [zendframework/zend-view#166]
Is there the possiblity to use `headLink` method for build a `<link rel='preload'...>` tag?  I've been trying use it but it didn't add the proprieties `as=font` and `crossorigin`.

More information about preload: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by thomasvargiu** [comment]
Hello @tcelestino 

Are you using the last release ([`2.10.0`](https://github.com/zendframework/zend-view/releases))?
Using `as` is allowed since this release with PR #138.

Can you provide an example on how you are trying to use it?

**Comment by tcelestino** [comment]
@thomasvargiu, the project doesn't use the last release because that is old project. 😢

```php
<?php headLink({'rel': 'preload', 'href': 'urlfont', 'as': 'font', 'crossorigin': 'true', 'type': 'font/woff'}); ?>
```

Thank for you help.
