### ISSUE TITLE
PHP 7.3 issue with compact() in HeadLink.php

### ISSUE THREAD

**Issue by unicarevcs** [zendframework/zend-view#172]
Under PHP 7.3 we see the following logged:
PHP Notice:  compact(): Undefined variable: extras in src\Helper\HeadLink.php on line 413

A quick fix replaces lines 408-413 with:
$attributes = compact('rel', 'type', 'href', 'media', 'conditionalStylesheet');

if ($args && is_array($args[0])) {
    $attributes['extras'] = array_shift($args);
}

**Comment by froschdesign** [comment]
We already have a pull request (#170) for this problem and will be released with the next bugfix release (2.10.1).

**Comment by Ocramius** [comment]
Closing as `duplicate`
