### ISSUE TITLE
HeadScript: handle empty type

### ISSUE THREAD

**Issue by matbech** [zendframework/zend-view#20]
The HeadScript view helper should handle an empty type. In HTML5 the type attribute is optional. It would be nice if we can pass an empty type to the append* methods which then results in the type attribute being omitted in the output.

```
function itemToString
...
        $type = ($this->autoEscape) ? $this->escape($item->type) : $item->type;
        $html = '<script type="' . $type . '"' . $attrString . '>';
```

**Comment by froschdesign** [comment]
Fixed with #21
