### ISSUE TITLE
Improve identity view helper factory

### ISSUE THREAD

**Issue by bogutskyy** [zendframework/zend-view#33]
I have a few problems with an identity view helper [factory](https://github.com/zendframework/zend-view/blob/master/src/Helper/Service/IdentityFactory.php).

```
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $services = $serviceLocator->getServiceLocator();
        $helper = new Identity();
        if ($services->has('Zend\Authentication\AuthenticationService')) {
            $helper->setAuthenticationService($services->get('Zend\Authentication\AuthenticationService'));
        }
        return $helper;
    }
```
1. First about a retrieving of auth service. Maybe will be better to use [Zend\Authentication\AuthenticationServiceInterface](https://github.com/zendframework/zend-authentication/blob/master/src/AuthenticationServiceInterface.php) instead of **Zend\Authentication\AuthenticationService** as name of the auth service?
2. By default [HelperPluginManager](https://github.com/zendframework/zend-view/blob/master/src/HelperPluginManager.php) doesn't contain main service container, and var **$services** can be null. But it seems in develop branch this factory class already modified.

**Comment by gscscnd** [comment]
> 1. First about a retrieving of auth service. Maybe will be better to use [Zend\Authentication\AuthenticationServiceInterface](https://github.com/zendframework/zend-authentication/blob/master/src/AuthenticationServiceInterface.php) instead of **Zend\Authentication\AuthenticationService** as name of the auth service?

See zendframework/zend-mvc-plugin-identity#9
