### ISSUE TITLE
Break with 2.6

### ISSUE THREAD

**Issue by datasage** [zendframework/zend-view#43]
It looks like a change for forward compatibility broke 2.6.

The constructor for HelperPluginManager was updated with the following signature:

`public function __construct(ContainerInterface $container, array $config = [])`

The factory class (AbstractPluginManagerFactory) does not pass in the new required argument

 `$plugins = new $pluginManagerClass;`

**Comment by Michal-sk** [comment]
Correct. Heres my post in apigility regarding this issue: https://github.com/zfcampus/zf-apigility/issues/155

**Comment by bacinsky** [comment]
Confirmed, this is not working also:
https://github.com/zendframework/zend-view/blob/master/src/Helper/Navigation/PluginManager.php#L58
https://github.com/zendframework/zend-view/blob/master/src/Helper/Navigation.php#L325

I really appreciate your work, but now it's so frustrating to go with ZF2, BC breaks occurs too often, almost every of my build fails overnight an I cannot continue my work even I'm on stable ZF2 version.

**Comment by samsonasik** [comment]
confirmed it is an issue when use zendframework/zendframework `~2.5.0` as well

**Comment by samsonasik** [comment]
I temporary add : 
```
 "zendframework/zend-view": "2.5.3 as 2.6.0",
```
in composer.json

**Comment by Michal-sk** [comment]
even better

**Comment by nepda** [comment]
+1

**Comment by gianarb** [comment]
Yes same problem :+1:

**Comment by simonbaudry** [comment]
Issue confirmed too.

**Comment by Atachi** [comment]
+1

**Comment by bgaillard** [comment]
We also encounter this issue.

**Comment by gianarb** [comment]
YES guys! :) Thanks for your feedback..
https://twitter.com/GianArb/status/700269646600077312

My suggestion is to add a temporary 
```json
zendframework/zend-view: "~2.5.0"
```
In order to use the old version of Zend\View

**Comment by gpelly-cf** [comment]
:+1:

**Comment by justinhogg** [comment]
Having the same issue, pinning to 2.5.2 works for us.

**Comment by pboxed** [comment]
+1

**Comment by VitaliyPekov** [comment]
+1

**Comment by koeaoe** [comment]
+1

**Comment by wtk13** [comment]
+1

**Comment by weierophinney** [comment]
Please stop with the +1's; we're aware of the issue and its widespread effects, and will have a fix out shortly.

**Comment by weierophinney** [comment]
Fixed in #44, and released with 2.6.1.

**Comment by price84** [comment]
:+1:

**Comment by bb-drummer** [comment]
Hello!
when I set back to 'dev-master' I get a "Call to a member function has() on null in .../zend-view/src/HelperPluginManager.php on line 312" now... is that related or did I just mess up my ServiceManager again? :D

**Comment by weierophinney** [comment]
@bb-drummer dev-master is the 2.6 series. Please see the latest comments on #43 and #45 for details. tl;dr: for now, please pin zend-view to `~2.5.0`. We need to update a few components that extend zend-view functionality to ensure they all work well together.

**Comment by bb-drummer** [comment]
oh ok, I am sorry, must have overseen that one O:) +1 you guys rock

**Comment by andsol** [comment]
+1
