### ISSUE TITLE
Error using $this->navigation('navigation')->breadcrumbs()->setPartial('something')

### ISSUE THREAD

**Issue by TRutte** [zendframework/zend-view#45]
Hi, getting the following error using the navigation helper on latest version! Current project is using 2.5.3. After update to latest 2.6.1 for testing I was getting the error.

Argument 1 passed to Zend\\View\\HelperPluginManager::__construct() must implement interface Interop\\Container\\ContainerInterface, none given

Backtrace:
Zend\View\Helper\Navigation\PluginManager::__construct() at Projectpath\vendor\zendframework\zend-view\src\Helper\Navigation\PluginManager.php: 58
Zend\View\Helper\Navigation\PluginManager::getPluginManager() at Projectpath\vendor\zendframework\zend-view\src\Helper\Navigation.php: 325
Zend\View\Helper\Navigation::findHelper() at Projectpath\vendor\zendframework\zend-view\src\Helper\Navigation.php: 151
Zend\View\Helper\Navigation::__call() at Projectpath\vendor\zendframework\zend-view\src\Helper\Navigation.php: 112
Zend\View\Helper\Navigation::__call()
main() at Projectpath\module\Application\view\layout\layoutTabs.phtml: 107
Zend\View\Renderer\PhpRenderer::render() at Projectpath\vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php: 502
Zend\View\Renderer\PhpRenderer::render() at Projectpath\vendor\zendframework\zend-view\src\View.php: 207
Zend\View\View::render() at Projectpath\vendor\zendframework\zend-mvc\src\View\Http\DefaultRenderingStrategy.php: 103
Zend\Mvc\View\Http\DefaultRenderingStrategy::render()
Zend\EventManager\EventManager::triggerListeners() at Projectpath\vendor\zendframework\zend-eventmanager\src\EventManager.php: 490
Zend\EventManager\EventManager::trigger() at Projectpath\vendor\zendframework\zend-eventmanager\src\EventManager.php: 214
Zend\EventManager\EventManager::completeRequest() at Projectpath\vendor\zendframework\zend-mvc\src\Application.php: 353
Zend\Mvc\Application::run() at Projectpath\vendor\zendframework\zend-mvc\src\Application.php: 328
main() at Projectpath\public\index.php: 18

**Comment by tmcnicholls** [comment]
+1

**Comment by weierophinney** [comment]
Can you provide the output of `composer info -i`, please? The error you're reporting is true of zend-view 2.6.0, but should not be true in 2.6.1 (as it makes the first argument optional, and includes a test to verify that). If you can provide that output, that will allow me to investigate further.

**Comment by webimpress** [comment]
Problem is in zend-view/src/Helper/Navigation/PluginManager.php line 58
https://github.com/zendframework/zend-view/blob/master/src/Helper/Navigation/PluginManager.php#L58

I have the same issue.

**Comment by tmcnicholls** [comment]
```
zendframework/zend-cache            2.6.1              provides a generic way to cache any data
zendframework/zend-config           2.6.0              provides a nested object property based user interface for accessing this configuration data within application code
zendframework/zend-console          2.6.0
zendframework/zend-escaper          2.5.1
zendframework/zend-eventmanager     2.6.2
zendframework/zend-filter           2.6.1              provides a set of commonly needed data filters
zendframework/zend-form             2.6.0
zendframework/zend-http             2.5.4              provides an easy interface for performing Hyper-Text Transfer Protocol (HTTP) requests
zendframework/zend-hydrator         1.0.0
zendframework/zend-i18n             2.6.0
zendframework/zend-inputfilter      2.5.5
zendframework/zend-json             2.6.1              provides convenience methods for serializing native PHP to JSON and decoding JSON to native PHP
zendframework/zend-loader           2.5.1
zendframework/zend-log              2.7.0              component for general purpose logging
zendframework/zend-math             2.6.0
zendframework/zend-modulemanager    2.6.1
zendframework/zend-mvc              2.6.1
zendframework/zend-navigation       2.5.1              provides support for managing trees of pointers to web pages
zendframework/zend-paginator        2.5.1
zendframework/zend-serializer       2.6.1              provides an adapter based interface to simply generate storable representation of PHP types by different facilities, and recover
zendframework/zend-servicemanager   2.7.5
zendframework/zend-session          2.5.2              manage and preserve session data, a logical complement of cookie data, across multiple page requests by the same client
zendframework/zend-stdlib           2.7.5
zendframework/zend-uri              2.5.2              a component that aids in manipulating and validating ┬╗ Uniform Resource Identifiers (URIs)
zendframework/zend-validator        2.6.0              provides a set of commonly needed validators
zendframework/zend-view             2.6.1              provides a system of helpers, output filters, and variable escaping
```

I have updated `Helper\Navigation\PluginManager.php` locally to have the same signature as has been changed in `HelperPluginManager`, and am now getting the following error instead:

```
Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'An alias "Zend\View\Helper\Navigation\Menu" was requested but no service could be found.' in \vendor\zendframework\zend-servicemanager\src\ServiceManager.php on line 551
```

**Comment by weierophinney** [comment]
Ah, okay; this has to do with components we haven't updated yet, but which are extending the zend-view `HelperPluginManager`. We'll make a priority of getting those updated. (We cannot roll a fix to zend-view, as it would then break forwards-compatibility with zend-servicemanager v3, which was the whole point of the 2.6 release.)

Until then, pin to `zendframework/zend-view:~2.5.3`. Once we get releases out for zend-navigation and zend-form, I'll update this issue.

**Comment by samsonasik** [comment]
I got the following error with Navigation as well, but may little different error:

```
Fatal error: 'continue' not in the 'loop' or 'switch' context in /Users/samsonasik/www/PrismMagicAdmin/vendor/zendframework/zend-view/src/Helper/Navigation/PluginManager.php on line 62
Call Stack
#	Time	Memory	Function	Location
1	0.0002	368728	{main}( )	.../index.php:0
2	0.0843	4939896	Zend\Mvc\Application->run( )	.../index.php:21
3	0.0945	5351360	Zend\Mvc\Application->completeRequest( )	.../Application.php:328
4	0.0945	5351360	Zend\EventManager\EventManager->trigger( )	.../Application.php:353
5	0.0945	5351416	Zend\EventManager\EventManager->triggerListeners( )	.../EventManager.php:214
6	0.0947	5353104	call_user_func:{/Users/samsonasik/www/PrismMagicAdmin/vendor/zendframework/zend-eventmanager/src/EventManager.php:490} ( )	.../EventManager.php:490
7	0.0947	5353104	Zend\Mvc\View\Http\DefaultRenderingStrategy->render( )	.../EventManager.php:490
8	0.0947	5353104	Zend\View\View->render( )	.../DefaultRenderingStrategy.php:103
9	0.1215	5373872	Zend\View\Renderer\PhpRenderer->render( )	.../View.php:207
10	0.1217	5411144	include( '/Users/samsonasik/www/MyProject/module/Application/view/layout/layout.phtml' )	.../PhpRenderer.php:502
11	0.1331	5936048	Zend\View\Helper\Navigation->menu( )	.../layout.phtml:55
12	0.1331	5936104	Zend\View\Helper\Navigation->__call( )	.../layout.phtml:55
13	0.1331	5936104	Zend\View\Helper\Navigation->findHelper( )	.../Navigation.php:112
14	0.1331	5936104	Zend\View\Helper\Navigation->getPluginManager( )	.../Navigation.php:151
15	0.1331	5936104	spl_autoload_call ( )	.../Navigation.php:325
16	0.1331	5936264	Composer\Autoload\ClassLoader->loadClass( )	.../Navigation.php:325
17	0.1331	5936424	Composer\Autoload\includeFile( )	.../ClassLoader.php:301
```

**Comment by weierophinney** [comment]
@samsonasik that's something else entirely; looks like a circular dependency issue. Report it against zend-navigation, please.

**Comment by samsonasik** [comment]
@weierophinney done, created at https://github.com/zendframework/zend-navigation/issues/19
