### ISSUE TITLE
Missing v2 cannonical FQSNs in Zend\View\Helper\Navigation\PluginManager.php (2.6.0 release)

### ISSUE THREAD

**Issue by webimpress** [zendframework/zend-view#46]
For backward compatibility we are missing in https://github.com/zendframework/zend-view/blob/master/src/Helper/Navigation/PluginManager.php#L47-L52 v2 canonical FQCNs:
```
    'zendviewhelpernavigationcreadcrumbs' => InvokableFactory::class,
    'zendviewhelpernavigationlinks' => InvokableFactory::class,
    'zendviewhelpernavigationmenu' => InvokableFactory::class,
    'zendviewhelpernavigationsitemap' => InvokableFactory::class,
```

as we have in: https://github.com/zendframework/zend-view/blob/master/src/HelperPluginManager.php#L186

(It was noticed by @tmcnicholls in https://github.com/zendframework/zend-view/issues/45#issuecomment-185736440)

**Comment by weierophinney** [comment]
I'll address this in #47; adding some code for this now.
