### ISSUE TITLE
__construct() must implement interface Interop\Container\ContainerInterface

### ISSUE THREAD

**Issue by sergeyzozulya** [zendframework/zend-view#48]
Same problem as described here: https://github.com/zendframework/zend-view/issues/43 (which is already fixed in 2.6.1)
Now it affects Zend\View\Helper\Navigation\PluginManager
Error: "__construct() must implement interface Interop\Container\ContainerInterface, none given"

**Comment by gianarb** [comment]
Yes same problem.. Duplicated issue

**Comment by weierophinney** [comment]
#47 will resolve this; just waiting for confirmation before merging and tagging 2.6.2.
