### ISSUE TITLE
Wrong namespace used inside FlashMessenger helper

### ISSUE THREAD

**Issue by h3d0n15m** [zendframework/zend-view#77]
Since version 3 the FlashMessenger plugin is no longer inside Zend\Mvc\Controller\Plugin namespace but in the FlashMessenger view helper the code is still the following:

**use Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;**

Changing the code to this makes it work again

**use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger as PluginFlashMessenger;**

**Comment by Renat123** [comment]
+1

**Comment by Rockstar04** [comment]
This is the same as #78?

There is also more going on here in #79 to more fully correct this.
