### ISSUE TITLE
$this->layout()->setTemplate('layout/admin'); in Controller __construct has no effect

### ISSUE THREAD

**Issue by armenio** [zendframework/zend-view#80]
namespace Admin\Controller;

class IndexController extends AbstractActionController
{
    public function __construct()
    {
        $this->layout()->setTemplate('layout/admin');
    }

**Comment by FabianKoestring** [comment]
You have to use following...
```php
$this->layout('layout/admin');
```

**Comment by weierophinney** [comment]
Plugins will not work from the constructor, as the plugin manager has not yet been injected. Either sweet it in your factory, or wait until the action is called.

**Comment by armenio** [comment]
As an example would be to do this in my factory?

**Comment by weierophinney** [comment]
Try this:

```php
// If using zend-servicemanager v2, do this first:
$container = $services->getServiceLocator();

// Then:
$plugins = $container->get('ControllerPluginManager');

$layout = $plugins->get('layout')->setTemplate('layout/admin');

// ... continue constructing your controller ...
return $controller;
```

**Comment by armenio** [comment]
I´m using Zf3 with default factory Zend\ServiceManager\Factory\InvokableFactory

assuming that I create my own factory,

I will have the method __invoke
__invoke(ContainerInterface $container, $requestedName, array $options = null)

With $container ready for use and need only follow with

// Then:
$plugins = $container->get('ControllerPluginManager');

$layout = $plugins->get('layout')->setTemplate('layout/admin');
