### ISSUE TITLE
Gravatar Helper with Attribs Method

### ISSUE THREAD

**Issue by wandersonwhcr** [zendframework/zend-view#87]
Hi

Conventionally, the method to configure attributes in Zend Framework is `setAttributes`. Gravatar helper uses `setAttribs` and the docs for Gravatar describes the helper with a `setAttributes` method. What is the correct form?

I'm questioning because I'll create a patch for it, dependending of your decision.

**Comment by froschdesign** [comment]
@wandersonwhcr 
Sorry for the late response.

> What is the correct form?

It should be `setAttributes`.

> I'll create a patch for it

We must mark the `setAttribs` method as deprecated and use this method as proxy to the new `setAttributes`.

Good catch! 👍

**Comment by wandersonwhcr** [comment]
@froschdesign Thanks. I'll create a PR.

**Comment by wandersonwhcr** [comment]
We must call a `trigger_error` with an `E_USER_WARNING` level?

**Comment by froschdesign** [comment]
Go for it!

**Comment by froschdesign** [comment]
Fixed with version [2.10.0](https://github.com/zendframework/zend-view/releases/tag/release-2.10.0)
